// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUbKymdVQKb1mKTGpwjW_m6U3YCl9jmUQ',
    appId: '1:881994165668:web:c0d9218ec893d85bb86531',
    messagingSenderId: '881994165668',
    projectId: 'manager-app-d5d6e',
    authDomain: 'manager-app-d5d6e.firebaseapp.com',
    storageBucket: 'manager-app-d5d6e.firebasestorage.app',
    measurementId: 'G-D9TN38CX9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaBUbBBX5nHXRHZDsL7Urv1Ae5PEof_dA',
    appId: '1:881994165668:android:8f0cbf2ab5dde431b86531',
    messagingSenderId: '881994165668',
    projectId: 'manager-app-d5d6e',
    storageBucket: 'manager-app-d5d6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1P6rjwzPr9SaqgL50u9NZswgj5dakYJA',
    appId: '1:881994165668:ios:0060b5f1e705f0b8b86531',
    messagingSenderId: '881994165668',
    projectId: 'manager-app-d5d6e',
    storageBucket: 'manager-app-d5d6e.firebasestorage.app',
    iosBundleId: 'com.example.managerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1P6rjwzPr9SaqgL50u9NZswgj5dakYJA',
    appId: '1:881994165668:ios:0060b5f1e705f0b8b86531',
    messagingSenderId: '881994165668',
    projectId: 'manager-app-d5d6e',
    storageBucket: 'manager-app-d5d6e.firebasestorage.app',
    iosBundleId: 'com.example.managerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUbKymdVQKb1mKTGpwjW_m6U3YCl9jmUQ',
    appId: '1:881994165668:web:fd7e2f0be49a2d2eb86531',
    messagingSenderId: '881994165668',
    projectId: 'manager-app-d5d6e',
    authDomain: 'manager-app-d5d6e.firebaseapp.com',
    storageBucket: 'manager-app-d5d6e.firebasestorage.app',
    measurementId: 'G-0VLNVG0WGG',
  );
}
