import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': {
          'welcome': 'مرحبا بعودتك من جديد!',
          'email': 'البريد الالكتروني',
          'password': 'الرقم السري',
          'login': 'تسحيل الدخول',
          'loginWord': 'سجل الدخول للمتابعة الى لوحة التحكم الخاصة بك',
          'forgetPassword': 'هل نسيت كلمة المرور؟',
          'dontHaveAccount': 'ليس لديك حساب؟',
          'haveAccount': 'بالفعل لديك حساب؟',
          'register': 'تسحيل الان',
          'registerBtn': 'سجل',
          'passwordConfirm': 'اعد ادخال كلمة المرور',
          'mobile': 'رقم الهاتف',
          'mobileErr': 'رقم الهاتف لا يمكن ان يكون فارغا!',
          'username': 'اسم المستخدم',
          'usernameErr': 'اسم المستخدم لا يمكن ان يكون فارغا!',
          'emailErr': 'برجاء ادخال البريد الالكتروني!',
          'passErr': 'برجاء ادخال كلمة المرور!',
          'passwordErr': 'برجاء ادخال كلمة المرور!',
          'confirmPassErr': 'برجاء ادخال كلمة المرور!',
          'weak-pass-err': 'جرب ادخال كلمة مرور اكثر قوة',
          'weak-pass': 'كلمة مرور ضعيفة',
          'email-already-in-use': 'البريد الالكتروني مستخدم بالفعل!',
          'email-already-in-use_err': 'جرب بريد الكتروني اخر!',
          'ok': 'حسنا',
          'cancel': 'الغاء',
          'error': 'خطأ',
          'unknown': 'خطأ غير معروف!',
        },
        'en': {
          'welcome': 'Welcome Back!',
          'email': 'Email',
          'password': 'Password',
          'login': 'Login',
          'loginWord': 'Login to continue manage your dashboard',
          'forgetPassword': 'Forget password?',
          'dontHaveAccount': 'Dont have an account?',
          'haveAccount': 'Already have an account?',
          'register': 'Register now',
          'registerBtn': 'Register',
          'passwordConfirm': 'Confirm your password',
          'mobile': 'Mobile ',
          'mobileErr': 'Mobile can\'t be empty!',
          'username': 'Username',
          'usernameErr': 'Username can\'t be empty!',
          'emailErr': 'Email can\'t be empty!',
          'passwordErr': 'Please enter your password!',
          'confirmPassErr': 'Please confirm your password!',
          'weak-pass': 'Weak password!',
          'weak-pass-err': 'Try a stronger password',
          'email-already-in-use': 'Email already in use!',
          'email-already-in-use-err': 'Try another email!',
          'ok': 'Ok',
          'cancel': 'Cancel',
          'error': 'Error',
          'unknown': 'Unknown error!',
          'successAddAccount': 'Account added successfully!',
        },
      };
}
